#!/bin/bash

# Main idea of this script is to add source files from optics_generator_python/src to PYTHON_PATH
# and folder root_libs to LD_LIBRARY_PATH. Other appended path are to fix bugs in SWAN environment or madx
path_to_SWAN_Projects=$HOME/SWAN_projects
folder_with_sources_name=optics_generator_python
path_to_root_libs=${path_to_SWAN_Projects}/${folder_with_sources_name}/root_libs
export PATH=$path_to_SWAN_Projects:$PATH
export PYTHONPATH=$PYTHONPATH:$path_to_SWAN_Projects/optics_generator_python/src
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path_to_root_libs:/cvmfs/sft.cern.ch/lcg/views/LCG_96python3/x86_64-centos7-gcc8-opt/lib:
source $path_to_SWAN_Projects/$folder_with_sources_name/commands_autocompletion.sh
# Download madx
MADX_PATH=$path_to_SWAN_Projects/madx
if ! test -f "$MADX_PATH"; then
    cd $path_to_SWAN_Projects
    wget -L http://madx.web.cern.ch/madx/releases/last-rel/madx-linux64-gnu
    mv madx-linux64-gnu $MADX_PATH
    chmod +700 $MADX_PATH
    rm madx-linux64-gnu
fi
# Compile library
if ! test -d "$path_to_root_libs"; then
    current_dir=`pwd`
    cd $path_to_SWAN_Projects
    cd $folder_with_sources_name
    cd src/root_classes/src
    make shared &
    cd $current_dir
fi